controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    #wheels
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # position_controller:
    #   type: position_controllers/JointGroupPositionController

#throttle
velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint

# position_controller:
#   ros__parameters:
#     joints:
#       - virtual_front_wheel_joint
