<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="carlikebot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="base_mass" value="10" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.240" />
  <xacro:property name="base_length" value="0.300" />
  <xacro:property name="base_height" value="0.140" />

  <xacro:property name="wheelbase" value=".2845" />
  <xacro:property name="wheel_width" value="0.0265" />
  <xacro:property name="wheel_radius" value="0.032" />
  <xacro:property name="wheel_mass" value="0.34055" /> <!-- arbitrary value for wheel mass -->
  
  <xacro:property name="friction" value="3"/>
  <xacro:property name="damping" value="0.01"/>

  <!-- ======================================================================================== -->
  
  <!-- Base Link -->
  <link name="${prefix}base_link"/>

  <!-- Chassis -->
  <link name="${prefix}chassis_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
      <geometry>
        <mesh filename="file://$(find carbot_hardware)/urdf/assets/Chassis.stl"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
      <geometry>
        <mesh filename="file://$(find carbot_hardware)/urdf/assets/Chassis.stl"/>
      </geometry>

      <material name="grey"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>
  </link>

    <gazebo reference="chassis_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="${prefix}chassis_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}chassis_link"/>
      <origin xyz="0 0 ${.0199 + wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="${damping}"/>
    </joint>

    <!-- ==================================================================== -->

    <xacro:macro name="wheel" params="name x y z front side">
        <link name="${name}_wheel">

            <!-- COLLISION -->
            <collision>
              <origin xyz="0 0 0" rpy="${side * -PI/2} 0 0"/>

              <geometry>
                <mesh filename="file://$(find carbot_hardware)/urdf/assets/Wheel.stl"/>
              </geometry>

              <surface>
                  <friction>
                    <ode>
                      <mu value="${friction}"/>
                      <mu2 value="${friction}"/>
                    </ode>
                  </friction>
                </surface>
            </collision>
      
            <!-- VISIUAL -->
            <visual>
                <origin xyz="0 0 0" rpy="${side * -PI/2} 0 0"/>

                <geometry>
                    <mesh filename="file://$(find carbot_hardware)/urdf/assets/Wheel.stl"/>
                </geometry>

                <material name="black"/>
            </visual>
      
            <!-- INERTIAL -->
            <inertial>
                <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
                <mass value="${wheel_mass}"/>
                <inertia
                    ixx="0.000270" ixy="0.0" ixz="0.0"
                    iyy="0.000270" iyz="0.0"
                    izz="0.000426"/>
            </inertial>
        </link>

        <gazebo reference="${name}_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <joint name="${name}_wheel_joint" type="continuous">
            <parent link="${prefix}chassis_link"/>
            <child link="${name}_wheel"/>
            <origin xyz="${front * .120} ${side * .129} -.0199" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit effort="1000.0" velocity="100.0"/>
            <dynamics damping="${damping}"/>

            <!-- <mimic joint="${prefix}virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/> -->
        </joint>

    </xacro:macro>

    <!-- ====================================================================================================== -->

    <xacro:wheel name="front_left" x="0" y="0" z="0" front="1" side="1"/>
    <xacro:wheel name="front_right" x="0" y="0" z="0" front="1" side="-1"/>
    <xacro:wheel name="rear_left" x="0" y="0" z="0" front="-1" side="1"/>
    <xacro:wheel name="rear_right" x="0" y="0" z="0" front="-1" side="-1"/>

  </xacro:macro>

</robot>
