<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="carlikebot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="10" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.1351" />
  <xacro:property name="base_length" value="0.1778" />
  <xacro:property name="base_height" value="0.030" />
  <xacro:property name="wheelbase" value="0.1778" />
  <xacro:property name="wheel_mass" value="0.34055" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.03" />
  <xacro:property name="wheel_radius" value="0.0375" />
  <xacro:property name="wheeltrack" value=".1651"/>
  <xacro:property name="friction" value="3"/>
  <xacro:property name="damping" value="0.01"/>

  <!-- ======================================================================================== -->
  <!-- Base Link -->
  <link name="${prefix}base_link" />

  <!-- Chassis -->

  <link name="${prefix}chassis_link">
    <!-- <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision> -->

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>
  </link>

    <gazebo reference="chassis_link">
      <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="${prefix}chassis_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}chassis_link"/>
      <origin xyz="0 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="${damping}"/>
    </joint>

    <!-- ==================================================================== -->

    <xacro:macro name="rear_wheel" params="name x y z direction">
        <link name="${name}_wheel">
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
                <geometry>
                  <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
                </geometry>
      
                <surface>
                  <friction>
                    <ode>
                      <mu value="${friction}"/>
                      <mu2 value="${friction}"/>
                    </ode>
                  </friction>
                </surface>
            </collision>
      
            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>

                <geometry>
                    <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
                </geometry>

                <material name="black"/>
            </visual>
      
            <inertial>
                <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
                <mass value="${wheel_mass}"/>
                <inertia
                    ixx="0.000270" ixy="0.0" ixz="0.0"
                    iyy="0.000270" iyz="0.0"
                    izz="0.000426"/>
            </inertial>
        </link>

        <gazebo reference="${name}_wheel">
            <material>Gazebo/Black</material>
          </gazebo>

        <joint name="${name}_wheel_joint" type="continuous">
            <parent link="${prefix}chassis_link"/>
            <child link="${name}_wheel"/>
            <origin xyz="-${wheelbase/2} ${base_width/2 * direction} -${base_height/2}" rpy="0 0 ${PI/2}"/>
            <axis xyz="1 0 0"/>
            <limit effort="1000.0" velocity="100.0"/>
            <dynamics damping="${damping}"/>

            <mimic joint="${prefix}virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
        </joint>

    </xacro:macro>

    <!-- =================================================================================================== -->

    <xacro:macro name="front_wheel" params="name x y z direction">
        <link name="${name}_wheel">
            <collision>
                <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
                <geometry>
                  <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
                </geometry>
      
                <surface>
                  <friction>
                    <ode>
                      <mu value="${friction}"/>
                      <mu2 value="${friction}"/>
                    </ode>
                  </friction>
                </surface>
            </collision>
      
            <visual>
                <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>

                <geometry>
                    <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
                </geometry>

                <material name="black"/>
            </visual>
      
            <inertial>
                <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
                <mass value="${wheel_mass}"/>
                <inertia
                    ixx="0.000270" ixy="0.0" ixz="0.0"
                    iyy="0.000270" iyz="0.0"
                    izz="0.000426"/>
            </inertial>
        </link>

        <link name="${name}_steer">
            <inertial>
                <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
                <mass value="${wheel_mass}"/>
                <inertia
                    ixx="0.000270" ixy="0.0" ixz="0.0"
                    iyy="0.000270" iyz="0.0"
                    izz="0.000426"/>
            </inertial>
        </link>

        <gazebo reference="${name}_wheel">
            <material>Gazebo/Black</material>
          </gazebo>

        <joint name="${name}_wheel_joint" type="continuous">
            <parent link="${name}_steer"/>
            <child link="${name}_wheel"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="1 0 0"/>
            <limit effort="100.0" velocity="100.0"/>
            <dynamics damping="${damping}"/>
            <mimic joint="${prefix}virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
        </joint>

        <joint name="${name}_steer_joint" type="revolute">
            <parent link="${prefix}chassis_link"/>
            <child link="${name}_steer"/>
            <origin xyz="${wheelbase/2} ${base_width/2 * direction} -${base_height/2}" rpy="0 0 ${PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit lower="-0.5" upper="0.5" effort="1000.0" velocity="0.0000001"/>
            <dynamics damping="${damping}"/>

            <mimic joint="${prefix}virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/>
        </joint>

    </xacro:macro>

    <!-- ====================================================================================================== -->

    <xacro:front_wheel name="front_left" x="0" y="0" z="0" direction="-1"/>
    <xacro:front_wheel name="front_right" x="0" y="0" z="0" direction="1"/>
    <xacro:rear_wheel name="rear_left" x="0" y="0" z="0" direction="-1"/>
    <xacro:rear_wheel name="rear_right" x="0" y="0" z="0" direction="1"/>

    <!-- virtual rear wheel -->

    <link name="${prefix}virtual_rear_wheel">

      <!-- <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
  
        <material name="invisible"/>
      </visual> -->

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>

    </link>

    <gazebo reference="${prefix}virtual_rear_wheel">
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${prefix}virtual_rear_wheel_joint" type="continuous">
      <parent link="${prefix}chassis_link"/>
      <child link="${prefix}virtual_rear_wheel"/>
      <origin xyz="-${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <dynamics damping="${damping}"/>
    </joint>

    <link name="${prefix}virtual_front_wheel">

      <!-- <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
  
        <material name="invisible"/>
      </visual> -->

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>
      
    </link>

    <gazebo reference="${prefix}virtual_front_wheel">
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${prefix}virtual_front_wheel_joint" type="revolute">
      <parent link="${prefix}chassis_link"/>
      <child link="${prefix}virtual_front_wheel"/>
      <origin xyz="${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.4" upper="0.4" effort="100.0" velocity="100.0"/>
      <dynamics damping="${damping}"/>
    </joint>


  </xacro:macro>

</robot>
