camera_driver_node:
  ros__parameters:
    camera_name: "camera"
    camera_frame_id: "camera_rig"
    camera_path: "/dev/v4l/by-path/pci-0000:00:14.0-usb-0:2:1.0-video-index0"
    # camera_index: 0
    publish_rate: 60.0 #hz
    publish_as_gray: true
    publish_compressed: true
    publish_camera_info: true

    resolution: [1280, 960]
    image_fps: 50

    