controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    #one controller for each side
    left_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_controller:
      type: velocity_controllers/JointGroupVelocityController

    # velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    # position_controller:
    #   type: position_controllers/JointGroupPositionController

    # effort_controller:
    #   type: effort_controllers/JointGroupEffortController

left_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - rear_left_wheel_joint

right_controller:
  ros__parameters:
    joints:
      - front_right_wheel_joint
      - rear_right_wheel_joint

#velo
# velocity_controller:
#   ros__parameters:
#     joints:
#       - front_left_wheel_joint
#       - front_right_wheel_joint
#       - rear_left_wheel_joint
#       - rear_right_wheel_joint

# position_controller:
#   ros__parameters:
#     joints:
#       - virtual_front_wheel_joint
