controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    #wheels
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    differential_drive_controller:
      type: differential_drive_controller/DifferentialDriveController

    # position_controller:
    #   type: position_controllers/JointGroupPositionController

#throttle
velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint

differential_drive_controller:
  ros__parameters:
    command_topic: /cmd_vel
    command_type: velocity
    feedback_types: ["velocity", "position"]
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheels_per_side: 2
    wheel_separation: 0.2845
    wheel_radius: 0.032

    odom_frame_id: ""
    base_frame_id: base_link

# position_controller:
#   ros__parameters:
#     joints:
#       - virtual_front_wheel_joint
