joystick_teleop:
  ros__parameters:
    joystick_type: "ps4" # implemented ones are: "ps4", "gamesir", "xbox" so far

    max_tangential_velocity: 1.0 # 1.0
    max_angular_velocity: 3.14 # 3.14

    # max_tangential_velocity: 0.0332 # 1.0
    # max_angular_velocity: 0.1 # 3.14